import Head from "next/head";

import { removeUserDetails } from "@/redux/reducers/User";
import { Box } from "@mui/material";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import Banner from "@/components/Home/Banner";
import AboutSection from "@/components/Home/About";

export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    const token = localStorage.getItem("accessToken");
    if (token) {
      localStorage.removeItem("accessToken");
      localStorage.removeItem("refreshToken");
      dispatch(removeUserDetails());
    }
  }, []);
  return (
    <>
      <Head>
        <title>MyTreks Parent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_mytreks.png" />
      </Head>
      <Box>
        {/* <Banner /> */}
        <Banner />
        <AboutSection />
      </Box>
    </>
  );
}
