export const enum COLORS {
  PRIMARY = "#FB5933",
  SECONDARY = "#fcb52e",
  LINEAR_GRADIENT = "linear-gradient(#FB5933, #FD9065)",
  TEXT_COLOR = "#737373",
  BLACK = "#000000",
  WHITE = "#ffffff",
  SIDEBAR_GRADIENT = "linear-gradient(#FFA893,#ffffff)",
  DANGER = "#FF0000",
  TRANSPARENT = "transparent",
  DONE = "#D3F9E1",
  DONE_TEXT = "#2F7B40",
}

export const enum USER_TYPE {
  STUDENT = "STUDENT",
  PARENT = "PARENT",
}

export const enum MEDIA_LIBRARY_TYPE {
  PROFILE = "PROFILE",
  GALLUP_RESULT = "GALLUP_RESULT",
}

export enum TOAST_STATUS {
  SUCCESS = "success",
  ERROR = "error",
  WARNING = "warning",
  INFO = "info",
}

export const GRADE = {
  8: "8th",
  9: "9th",
  10: "10th",
  11: "11th",
  12: "12th",
  HOMESCHOOLED: "Homeschooled",
};

export const RELATIONSHIP_DATA = {
  PARENT: "Parent",
  FATHER: "Father",
  MOTHER: "Mother",
  GUARDIAN: "Guardian",
  STEP_FATHER: "Stepfather",
  STEP_MOTHER: "Stepmother",
  SIBLING: "Sibling",
  BROTHER: "Brother",
  SISTER: "Sister",
  HALF_BROTHER: "Half-brother",
  HALF_SISTER: "Half-sister",
  GRANDPARENT: "Grandparent",
  GRANDFATHER: "Grandfather",
  GRANDMOTHER: "Grandmother",
  AUNT: "Aunt",
  UNCLE: "Uncle",
  COUSIN: "Cousin",
  CHILD: "Child",
  DAUGHTER: "Daughter",
  SON: "Son",
  NIECE: "Niece",
  NEPHEW: "Nephew",
  IN_LAW: "In-law",
  FATHER_IN_LAW: "Father-in-law",
  MOTHER_IN_LAW: "Mother-in-law",
  BROTHER_IN_LAW: "Brother-in-law",
  SISTER_IN_LAW: "Sister-in-law",
  SON_IN_LAW: "Son-in-law",
  DAUGHTER_IN_LAW: "Daughter-in-law",
  STEPSON: "Stepson",
  STEPDAUGHTER: "Stepdaughter",
  LEGAL_GUARDIAN: "Legal Guardian",
  FOSTER_PARENT: "Foster Parent",
  CASEWORKER: "Caseworker",
  COUNSELOR: "Counselor",
  ADVISOR: "Advisor",
  MENTOR: "Mentor",
  COACH: "Coach",
  FRIEND: "Friend",
  NEIGHBOR: "Neighbor",
  SPONSOR: "Sponsor",
  SELF: "Self",
  OTHER: "Other",
};

export const GENDER_DATA = {
  MALE: "Male",
  FEMALE: "Female",
  NON_BINARY: "Non-binary",
  TRANSGENDER_MALE: "Transgender Male",
  TRANSGENDER_FEMALE: "Transgender Female",
  GENDERQUEER: "Genderqueer",
  GENDERFLUID: "Genderfluid",
  AGENDER: "Agender",
  TWO_SPIRIT: "Two-Spirit (Native American/Indigenous cultures)",
  INTERSEX: "Intersex",
  GENDER_VARIANT: "Gender Variant",
  GENDER_NON_CONFORMING: "Gender Non-conforming",
  NEUTROIS: "Neutrois",
  ANDROGYNOUS: "Androgynous",
  THIRD_GENDER: "Third Gender",
  XENOGENDER: "Xenogender",
  MAVERIQUE: "Maverique",
  ALIAGENDER: "Aliagender",
  NOVIGENDER: "Novigender",
  APOGENDER: "Apogender",
  BLURGENDER: "Blurgender",
  DEMIGENDER: "Demigender",
  DEMIBOY: "Demiboy",
  DEMIGIRL: "Demigirl",
  LIBRAGENDER: "Libragender",
  PANGENDER: "Pangender",
  POLYGENDER: "Polygender",
  OMNIGENDER: "Omnigender",
  GREYGENDER: "Greygender",
  EPICENE: "Epicene",
  CETEROGENDER: "Ceterosexual",
  TRANSMASCULINE: "Transmasculine",
  TRANSFEMININE: "Transfeminine",
  TRANS_WOMAN: "Trans Woman",
  TRANS_MAN: "Trans Man",
  TRANSSEXUAL: "Transsexual",
  HIJRA: "Hijra (South Asian gender identity)",
  MUXE: "Muxe (Zapotec cultural identity)",
  FAAFAFINE: "Fa’afafine (Samoan gender identity)",
  FAKALEITI: "Fakaleiti (Tongan gender identity)",
  KATHOEY: "Kathoey (Thai gender identity)",
  WARIA: "Waria (Indonesian gender identity)",
  BIGENDER: "Bigender",
  TRIGENDER: "Trigender",
  GENDERFLUX: "Genderflux",
  GENDERFAE: "Genderfae",
  GENDERPUNK: "Genderpunk",
  AUTIGENDER: "Autigender",
  CASSGENDER: "Cassgender",
  CLOUDGENDER: "Cloudgender",
  OTHER: "Other (free-text field)",
  PREFER_NOT_TO_SAY: "Prefer Not to Say",
};

export enum USER_STATUS {
  ACTIVE = "Active",
  INACTIVE = "Inactive",
}

export enum SOCIAL_LOGIN {
  GOOGLE = "GOOGLE",
  APPLE = "APPLE",
}

export enum DEVICE_TYPE {
  WEB = "WEB",
  ANDROID = "ANDROID",
  IOS = "IOS",
}
